name: Prebuild

on:
  push:
    tags:
      - v*
    branches:
      - '*'
jobs:
  test:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [12, 14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node}}

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 6

    - name: Build and test
      run: |
        pnpm i
        pnpm test
      env:
        CI: true

    - name: prebuild node 12
      if: ${{ matrix.node == 12 }}
      run: pnpm prebuild -- -t 12.0.0 -t electron@9.3.5 -t electron@12.0.0
      env:
        CI: true

    - name: prebuild node 14
      if: ${{ matrix.node == 14 }}
      run: pnpm prebuild -- -t 14.0.0  -t electron@12.0.0
      env:
        CI: true    

    - name: prebuild node 12 ia32
      if: ${{ contains(matrix.os, 'windows') && matrix.node == 12 }}
      run: pnpm prebuild -- -t 12.0.0 -t electron@9.3.5 -t electron@12.0.0 --arch=ia32
      env:
        CI: true

    - name: prebuild node 14 ia32
      if: ${{ contains(matrix.os, 'windows') && matrix.node == 14 }}
      run: pnpm prebuild -- -t 14.0.0  -t electron@12.0.0 --arch=ia32
      env:
        CI: true

    - name: Upload articats
      uses: actions/upload-artifact@v2
      with:
        path: ./prebuilds

  #   manually download the artifact and publish
  # publish:
  #   name: Publish builds to release
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js 12.x
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 12.x
  #
  #   - name: Download articats
  #     uses: actions/download-artifact@v2
  #
  #   - name: Upload to Release
  #     run: |
  #       mkdir prebuilds
  #       rsync -a artifact/ prebuilds/
  #       pnpm i --ignore-scripts
  #       pnpx prebuild --upload-all ${{ secrets.GITHUB_TOKEN }}
