name: Node CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 5

    - name: Install, build, and test
      run: |
        pnpm i
        pnpm test
      env:
        CI: true
